apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dv2ckzpnk-python
  janus-idp.io/tekton: dv2ckzpnk-python
  backstage.io/kubernetes-id: dv2ckzpnk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dv2ckzpnk-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
