apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dv2ckzpnk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dv2ckzpnk-python 
  name: dv2ckzpnk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dv2ckzpnk-python 
